name: Deploy pleiepenger - livets sluttfase topics

env:
  TOPICS_PATH: 'nais/topics/pleiepenger-livets-sluttfase-topics.yml'

on:
  push:
    paths:
      - '.github/workflows/deploy-pils-topics.yml'
      - '.github/workflows/reusable-topic-workflow.yml'
      - 'nais/topics/pleiepenger-livets-sluttfase-topics.yml'

jobs:
  deploy-pils-topics:
    permissions:
      id-token: write
    uses: ./.github/workflows/reusable-topic-workflow.yml
    with:
      job-name: pils-topics
      topics-path: 'nais/topics/pleiepenger-livets-sluttfase-topics.yml'
    secrets: inherit
