package no.nav.brukerdialog.ytelse.pleiepengersyktbarn.søknad.pdf

val PdfTekster: Map<String, String> =
    mapOf(
        "innsendingsdetaljer.tittel" to "Innsendingsdetaljer",
        "innsendingsdetaljer.innsendtTidspunk" to "Send til Nav",
        "søker.tittel" to "Søker",
        "søker.navnSøker" to "Navn",
        "søker.fødselsnummerSøker" to "Fødselsnummer",
        "søker.navnBarn" to "Navn på barn",
        "søker.fødselsnummerBarn" to "Fødselsnummer på barn",
        "barnrelasjon.tittel" to "Relasjon til barnet",
        "barnrelasjon.relasjon" to "Hvilken relasjon har du til barnet?",
        "barnrelasjon.relasjon.beskrivelse" to "Din beskrivelse av relasjon og tilsynsrolle for barnet:",
        "perioder.tittel" to "Perioder du søker om pleiepenger",
        "perioder.hvilkePeriode" to "Hvilke periode har du søkt om pleiepenger?",
        "arbeidsgivere.tittel" to "Arbeidsgivere",
        "arbeidsgiver.navnOgOrgnr" to "{0} (orgnr: {1})",
        "arbeidsgiver.erAnsatt" to "Jobber du her nå?",
        "arbeidsgiver.sluttetFørSøknadsperiode" to "Sluttet du hos {0} før {1}?",
        "arbeidsgiver.timerPerUkeNormalt" to "Hvor mange timer jobber du normalt per uke?",
        "arbeidsgivere.ingenArbeidsforhold" to "Arbeidsforhold",
        "stønadGodtgjørelse.tittel" to "Omsorgsstønad eller fosterhjemsgodtgjørelse",
        "stønadGodtgjørelse.mottarStønadGodtgjørelse" to "Mottar du omsorgsstønad eller fosterhjemsgodtgjørelse?",
        "stønadGodtgjørelse.startetUnderveis" to "Startet du å motta dette underveis i perioden du søker for?",
        "stønadGodtgjørelse.sluttetUnderveis" to "Slutter du å motta dette underveis i perioden du søker for?",
//        "frilans.tittel" to Tekst("Frilans"),
//        "frilans.jobberSomFrilanser" to Tekst("Jobber som frilanser"),
//        "frilans.jobberSomFrilanserEllerMottarHonorar" to Tekst("Jobber du som frilanser eller mottar du honorarer?", svar = "{0}"),
//        "frilans.startetFør3Måneder" to Tekst("Startet du som frilanser før {0}?", svar = "{0}"),
//        "frilans.nårStartet" to Tekst("Når startet du som frilanser?", svar = "{0}"),
//        "frilans.fremdeles" to Tekst("Jobber du fremdeles som frilanser?", svar = "{0}"),
//        "frilans.nårSluttet" to Tekst("Når sluttet du som frilanser?", svar = "{0}"),
//        "frilansOgHonorar.jobberSomOgMottar" to Tekst("Jobber som frilanser og mottar honorar"),
//        "frilansOgHonorar.startetFør3Måneder" to Tekst("Startet du som frilanser/startet å motta honorar før {0}?", svar = "{0}"),
//        "frilansOgHonorar.nårStartet" to Tekst("Når begynte du å jobbe som frilanser/startet å motta honorar?", svar = "{0}"),
//        "frilansOgHonorar.fremdeles" to Tekst("Jobber du fremdeles som frilanser/mottar honorar?", svar = "{0}"),
//        "frilansOgHonorar.nårSluttet" to Tekst("Når sluttet du som frilanser/sluttet å motta honorar?", svar = "{0}"),
//        "honorar.mottarHonorar" to Tekst("Mottar honorar"),
//        "honorar.startetFør3Måneder" to Tekst("Startet du og motta honorar før {0}?", svar = "{0}"),
//        "honorar.nårStartet" to Tekst("Når begynte du å motta honorar?", svar = "{0}"),
//        "honorar.fremdeles" to Tekst("Mottar du fortsatt honorar?", svar = "{0}"),
//        "honorar.nårSluttet" to Tekst("Når sluttet du å motta honorar?", svar = "{0}"),
//        "honorar.misterHonorar" to Tekst("Jeg mister honorar i søknadsperioden"),
//        "honorar.misterIkkeHonorar" to Tekst("Jeg mister ikke honorar i søknadsperioden"),
//        "ikkeFrilansEllerHonorar" to Tekst("Har ikke vært frilanser eller mottatt honorar i perioden det søkes om."),
//        "frilans.arbeidIPerioden" to Tekst("Arbeid i perioden", svar = "{0}"),
    )
